# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import evaluator_pb2 as evaluator__pb2


class EvaluatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Eval = channel.unary_unary(
        '/Evaluator/Eval',
        request_serializer=evaluator__pb2.Expr.SerializeToString,
        response_deserializer=evaluator__pb2.Expr.FromString,
        )


class EvaluatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Eval(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EvaluatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Eval': grpc.unary_unary_rpc_method_handler(
          servicer.Eval,
          request_deserializer=evaluator__pb2.Expr.FromString,
          response_serializer=evaluator__pb2.Expr.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Evaluator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
