# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evaluator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='evaluator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x65valuator.proto\"\'\n\x04\x45xpr\x12\x0f\n\x07str_exp\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\x05\x32#\n\tEvaluator\x12\x16\n\x04\x45val\x12\x05.Expr\x1a\x05.Expr\"\x00\x62\x06proto3')
)




_EXPR = _descriptor.Descriptor(
  name='Expr',
  full_name='Expr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_exp', full_name='Expr.str_exp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='Expr.output', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Expr'] = _EXPR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Expr = _reflection.GeneratedProtocolMessageType('Expr', (_message.Message,), dict(
  DESCRIPTOR = _EXPR,
  __module__ = 'evaluator_pb2'
  # @@protoc_insertion_point(class_scope:Expr)
  ))
_sym_db.RegisterMessage(Expr)



_EVALUATOR = _descriptor.ServiceDescriptor(
  name='Evaluator',
  full_name='Evaluator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=60,
  serialized_end=95,
  methods=[
  _descriptor.MethodDescriptor(
    name='Eval',
    full_name='Evaluator.Eval',
    index=0,
    containing_service=None,
    input_type=_EXPR,
    output_type=_EXPR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVALUATOR)

DESCRIPTOR.services_by_name['Evaluator'] = _EVALUATOR

# @@protoc_insertion_point(module_scope)
